# fly.toml app configuration file generated for aprende-ai on 2023-05-04T20:11:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aprende-ai"
primary_region = "gig"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
