# fly.toml app configuration file generated for aprende-ai-white-sun-4587 on 2024-09-21T15:28:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "aprende-ai"
primary_region = "gig"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
